spring:
  datasource:
    username: vlad
    url: jdbc:postgresql://localhost:5432/postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api
